name: Build firmware
on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:


jobs:
  build-firmware:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    strategy:
      fail-fast: false
      matrix:
        keymap:
          - default
          - oryx

    steps:
    - name: Checkout QMK Firmware
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        persist-credentials: false
        submodules: true

    - name: Build
      id: build
      run: |
        qmk mass-compile -f manufacturer="ZSA Technology Labs" -km ${{ matrix.keymap }} -e SKIP_GIT=1
